/* 此处存放全局公共数据 */
var Width = 1200
var Height = 900
var leg = 0 // 元素名称后面添加的标识, 此数值会不断累加,防止名称相同
var delIndex = null // 删除元素下标
var menu = document.querySelector("#rightMenu");  //获取自定义的右键菜单
var commonList = {
  Title: '画布',
  Name: 'MainCanvas'
}
// 左侧按钮组
var btns = [
  {
    icon: 'iconjingtaitupian-copy',
    title: '静态图片',
    ControlType: 'staticimage',
    Width: 100,
    Height: 30,
    Img: './imgs/img1.jpg',
    Opacity: 100,
    ZIndex: 10,
  },
  {
    icon: 'iconjingtaitupian-copy',
    title: '动态图片',
    ControlType: 'image',
    Width: 100,
    Height: 30,
    Img: './imgs/img1.jpg',
    Opacity: 100,
    ZIndex: 10,
  },
  {
    icon: 'iconwenben',
    title: '数值显示',
    ControlType: 'datatextblock',
    Width: 100,
    Height: 30,
    FontFamily: '微软雅黑',
    FontWeight: 'normal',
    FontSize: 12,
    TextDecoration: 'none',
    Color: '#000',
    BackColor: '#fff',
    BorderWidth: 0,
    Style: 'solid',
    BorderColor: '#000',
    Opacity: 100,
    ZIndex: 10,
  },
  {
    icon: 'iconzhixian_huaban1',
    title: '直线',
    ControlType: 'line',
    Width: 100,
    Height: 2,
    BorderWidth: 2,
    Style: 'solid',
    BorderColor: '#000',
    Opacity: 100,
    ZIndex: 10,
  },
  {
    icon: 'iconrect',
    title: '矩形',
    ControlType: 'solidrectangle',
    BackColor: '#fff',
    BorderWidth: 2,
    Style: 'solid',
    BorderColor: '#000',
    Width: 100,
    Height: 30,
    Opacity: 100,
    ZIndex: 10,
  },
  {
    icon: 'iconradio-on-full',
    title: '圆形',
    ControlType: 'solidellipse',
    BackColor: '#fff',
    BorderWidth: 2,
    Style: 'solid',
    BorderColor: '#000',
    Width: 100,
    Height: 30,
    Opacity: 100,
    ZIndex: 10,
  },
  {
    icon: 'iconjinggao',
    title: '圆形状态灯',
    ControlType: 'ellipselamp',
    Width: 30,
    Height: 30,
    Opacity: 100,
    ZIndex: 10,
  },
  {
    icon: 'iconrect',
    title: '矩形状态灯',
    ControlType: 'commonlamp',
    Width: 100,
    Height: 30,
    BorderRadius: 10,
    Opacity: 100,
    ZIndex: 10,
  },
  {
    icon: 'iconwenben',
    title: '静态文本',
    ControlType: 'statictextblock',
    FontFamily: '微软雅黑',
    FontWeight: 'normal',
    FontSize: 12,
    TextDecoration: 'none',
    Color: '#000',
    Opacity: 100,
    Text: '静态文本',
    BackColor: '#fff',
    Width: 100,
    Height: 30,
    ZIndex: 10,
  },
  {
    icon: 'iconwenben',
    title: '动态文本',
    ControlType: 'dynamictext',
    Width: 100,
    Height: 30,
    FontFamily: '微软雅黑',
    FontWeight: 'normal',
    FontSize: 12,
    TextDecoration: 'none',
    Color: '#000',
    Opacity: 100,
    TextAlign: 'center',
    Text: '动态文本',
    ZIndex: 10,
  },
  {
    icon: 'iconanniu',
    title: '控制按钮',
    ControlType: 'cornerbutton',
    Width: 100,
    Height: 30,
    FontFamily: '微软雅黑',
    FontWeight: 'normal',
    Color: '#000',
    BackColor: '#ddd',
    FontSize: 12,
    TextAlign: 'center',
    BorderWidth: 1,
    Style: 'solid',
    BorderColor: '#000',
    BorderRadius: 10,
    Text: '控制按钮',
    Opacity: 100,
    ZIndex: 10,
  },
  {
    icon: 'iconShapecopy',
    title: '读写框',
    ControlType: 'rwtextbox',
    Width: 100,
    Height: 30,
    FontFamily: '微软雅黑',
    FontWeight: 'normal',
    Color: '#000',
    BackColor: '#fff',
    FontSize: 12,
    TextAlign: 'center',
    BorderWidth: 1,
    Style: 'solid',
    BorderColor: '#ABADB3',
    BorderRadius: 0,
    Text: '读写框',
    Opacity: 100,
    ZIndex: 10,
  },
  {
    icon: 'iconlianjie',
    title: '跳转链接',
    ControlType: 'jumplink',
    Width: 100,
    Height: 30,
    FontFamily: '微软雅黑',
    FontWeight: 'normal',
    FontSize: 12,
    BackColor: '#fff',
    Color: '#000',
    Text: '盛原成',
    Opacity: 100,
    ZIndex: 10,
  },
  {
    icon: 'iconchaxun',
    title: '文本查询',
    ControlType: 'textsearch',
    Width: 100,
    Height: 30,
    FontFamily: '微软雅黑',
    FontWeight: 'normal',
    FontSize: 12,
    BorderWidth: 1,
    Placeholder: '请输入关键词',
    Style: 'solid',
    BorderColor: '#ABADB3',
    BackColor: '#fff',
    TextAlign: 'left',
    Color: '#000',
    BorderRadius: 0,
    Text: '',
    Opacity: 100,
    ZIndex: 10,
  }
]

var Controls = {
  ControlList: []
}
Controls.ControlList = [
  {
    title: '矩形',
    ControlType: 'solidrectangle',
    Name: 'solidrectangle0',
    PropertyList: {
      id: 0,
      Left: 100,
      Top: 500,
      Width: 200,
      Height: 140,
      BackColor: '#fff',
      BorderWidth: 2,
      Style: 'solid',
      BorderColor: '#000',
      Opacity: 100,
      ZIndex: 10
   },
    pointList: ['lt', 'rt', 'lb', 'rb', 'l', 'r', 't', 'b'],
  },
  {
    title: '直线',
    ControlType: 'line',
    Name: 'line1',
    PropertyList: {
      id: 1,
      Left: 400,
      Top: 200,
      Width: 100,
      BorderWidth: 5,
      height: 5,
      Style: 'solid',
      Opacity: 100,
      BorderColor: '#000',
      ZIndex: 10
   },
    pointList: ['l', 'r'],
  }
]
// 数值显示组件变量表格数据
var tableData = []
