/* 此处存放全局公共数据 */
var Width = 1200
var Height = 900
var leg = 0 // 元素名称后面添加的标识, 此数值会不断累加,防止名称相同
var zindex = 0; //层级
var revoke = [[]]; //撤销的数据
var delIndex = null // 删除元素下标
var firstback = false;
var firsright = false;
var handtrue = false;
var viewpass = [1]
var  backtmp = []//中间存放数组
var localdata = {
  ControlList:[],
  Data:{
    
  }
} //局部渲染数据
var menu = document.querySelector("#rightMenu");  //获取自定义的右键菜单
// 储存copy数据
var copydata = []
// 储存cut数据
var cutdata = [];
// 储存恢复的数组
var recovery = [];
var commonList = {
  Name: 'MainCanvas',
  Position: '根目录',
  BackSetting: 'color',
  BackColor: '#fff',
  BackImg: '',
  Permision: '大聪明',
  Description: ''
}
// 线型
var lineList = ['dotted','dashed','solid','double','groove','ridge','inset','outset']
// 按钮id
var buttonid = ''
// 判断是否按过ctrl
var type = ''
// 选中数据
var selectdata = [] 
// 组件按钮组
var btns = [
  {
    icon: 'icontupian',
    title: '静态图片',
    ComName: '静态图片',  //组件名称
    ControlType: 'staticimage',
    Width: 100,
    Height: 30,
    Rotate: 0,
    Img: './imgs/img1.jpg',
    BorderColor: '#000',
    BackColor: '#fff',
    BorderWidth: 0,
    Style: 'solid',
    BorderRadius: 3,
    BoxShadow: '',
    Opacity: 100,
    ZIndex: 10,
  },
  {
    icon: 'icondongtaitupian',
    title: '动态图片',
    ControlType: 'image',
    Width: 100,
    Height: 30,
    Rotate: 0,
    Img: './imgs/img1.jpg',
    Opacity: 100,
    ZIndex: 10,
  },
  {
    icon: 'iconshuzhixianshi',
    title: '数值显示',
    ControlType: 'datatextblock',
    Width: 100,
    Height: 30,
    FontFamily: '微软雅黑',
    FontWeight: 'normal',
    FontSize: 12,
    TextDecoration: 'none',
    Color: '#000',
    BackColor: '#fff',
    BorderWidth: 0,
    Style: 'solid',
    BorderColor: '#000',
    Opacity: 100,
    ZIndex: 10,
  },
  {
    icon: 'iconzhixian',
    title: '直线',
    ControlType: 'line',
    Width: 100,
    Height: 2,
    BorderWidth: 2,
    Style: 'solid',
    BorderColor: '#000',
    Opacity: 100,
    ZIndex: 10,
  },
  {
    icon: 'iconkuangti',
    title: '矩形',
    ControlType: 'solidrectangle',
    BackColor: '#fff',
    BorderWidth: 2,
    Rotate: 0,
    Style: 'solid',
    BorderColor: '#000',
    BoxShadow: '',
    Width: 100,
    Height: 30,
    Opacity: 100,
    ZIndex: 10,
  },
  {
    icon: 'iconkuangti_yuan',
    title: '圆形',
    ControlType: 'solidellipse',
    BackColor: '#fff',
    BorderWidth: 2,
    Style: 'solid',
    BorderColor: '#000',
    Width: 100,
    Height: 30,
    Opacity: 100,
    ZIndex: 10,
  },
  {
    icon: 'iconzhuangtaidian',
    title: '圆形状态灯',
    ControlType: 'ellipselamp',
    Width: 30,
    Height: 30,
    Opacity: 100,
    ZIndex: 10,
  },
  {
    icon: 'iconzhuangtaidian_juxing',
    title: '矩形状态灯',
    ControlType: 'commonlamp',
    Width: 100,
    Height: 30,
    BorderRadius: 10,
    Opacity: 100,
    ZIndex: 10,
  },
  {
    icon: 'iconwenben',
    title: '静态文本',
    ControlType: 'statictextblock',
    FontFamily: '微软雅黑',
    FontWeight: 'normal',
    FontSize: 12,
    TextDecoration: 'none',
    Color: '#000',
    Opacity: 100,
    Text: '静态文本',
    BackColor: '#fff',
    Width: 100,
    Height: 30,
    ZIndex: 10,
  },
  {
    icon: 'icondongtaiwenben',
    title: '动态文本',
    ControlType: 'dynamictext',
    Width: 100,
    Height: 30,
    FontFamily: '微软雅黑',
    FontWeight: 'normal',
    FontSize: 12,
    TextDecoration: 'none',
    Color: '#000',
    Opacity: 100,
    ComName: '动态文本',  //组件名称
    BackColor: '#fff',
    BorderColor: '#000',
    BorderWidth: 0,
    Style: 'solid',
    BorderRadius: 3,
    BoxShadow: '',
    Rotate: 0,
    TextAlign: 'center',
    Text: '动态文本',
    ZIndex: 10,
  },
  {
    icon: 'iconkongzhianniu',
    title: '控制按钮',
    ControlType: 'cornerbutton',
    Width: 100,
    Height: 30,
    FontFamily: '微软雅黑',
    FontWeight: 'normal',
    Color: '#000',
    BackColor: '#ddd',
    FontSize: 12,
    TextAlign: 'center',
    BorderWidth: 1,
    Style: 'solid',
    BorderColor: '#000',
    BorderRadius: 10,
    Text: '控制按钮',
    Opacity: 100,
    ZIndex: 10,
  },
  {
    icon: 'iconduxiekuang',
    title: '读写框',
    ControlType: 'rwtextbox',
    Width: 100,
    Height: 30,
    FontFamily: '微软雅黑',
    FontWeight: 'normal',
    Color: '#000',
    BackColor: '#fff',
    FontSize: 12,
    TextAlign: 'center',
    BorderWidth: 1,
    Style: 'solid',
    BorderColor: '#ABADB3',
    BorderRadius: 0,
    Text: '读写框',
    Opacity: 100,
    ZIndex: 10,
  },
  {
    icon: './imgs/icon_link.png',
    title: '跳转链接',
    ControlType: 'jumplink',
    Width: 100,
    Height: 30,
    FontFamily: '微软雅黑',
    FontWeight: 'normal',
    FontSize: 12,
    BackColor: '#fff',
    Color: '#000',
    Text: '盛原成',
    Opacity: 100,
    ZIndex: 10,
  },
  {
    icon: 'iconwenbenchaxun',
    title: '文本查询',
    ControlType: 'textsearch',
    Width: 230,
    Height: 30,
    FontFamily: '微软雅黑',
    FontWeight: 'normal',
    FontSize: 12,
    BorderWidth: 1,
    Value: '',
    Placeholder: '请输入关键词',
    Style: 'solid',
    BorderColor: '#ABADB3',
    BackColor: '#fff',
    TextAlign: 'left',
    Color: '#000',
    BorderRadius: 0,
    Text: '',
    Opacity: 100,
    ZIndex: 10,
  },
  {
    icon: 'iconriqishijian',
    title: '日期时间',
    ControlType: 'associatedatetimepicker',
    Width: 160,
    Height: 30,
    FontFamily: '微软雅黑',
    FontWeight: 'normal',
    FontSize: 12,
    BorderWidth: 1,
    Style: 'solid',
    BorderColor: '#ABADB3',
    BackColor: '#fff',
    TextAlign: 'left',
    Color: '#000',
    BorderRadius: 0,
    Text: '',
    Date: new Date,
    Opacity: 100,
    ZIndex: 10,
  },
  {
    icon: 'iconshuzhichaxun',
    title: '数值查询',
    ControlType: 'datasearch',
    Width: 330,
    Height: 30,
    FontFamily: '微软雅黑',
    FontWeight: 'normal',
    FontSize: 12,
    BorderWidth: 1,
    Placeholder: '请输入数值',
    Value: '等于',
    Num1: '',
    Num2: '',
    Style: 'solid',
    BorderColor: '#ABADB3',
    BackColor: '#fff',
    TextAlign: 'left',
    Color: '#000',
    BorderRadius: 0,
    Text: '',
    Opacity: 100,
    ZIndex: 10,
  },
  {
    icon: 'iconxialachaxun',
    title: '下拉查询',
    ControlType: 'dropsearch',
    Width: 260,
    Height: 30,
    FontFamily: '微软雅黑',
    FontWeight: 'normal',
    FontSize: 12,
    BorderWidth: 1,
    Placeholder: '请输入关键词',
    Value: '不限',
    CheckedValue: '',
    Style: 'solid',
    BorderColor: '#ABADB3',
    BackColor: '#fff',
    TextAlign: 'left',
    Color: '#000',
    BorderRadius: 0,
    Disabled: false,
    Text: '',
    Opacity: 100,
    ZIndex: 10,
  },
  {
    icon: 'iconchaxunanniu',
    title: '查询按钮',
    ControlType: 'searchbutton',
    Width: 100,
    Height: 30,
    FontFamily: '微软雅黑',
    FontWeight: 'normal',
    Color: '#000',
    BackColor: '#ddd',
    FontSize: 12,
    TextAlign: 'center',
    BorderWidth: 1,
    Style: 'solid',
    BorderColor: '#000',
    BorderRadius: 10,
    Text: '查询按钮',
    Opacity: 100,
    ZIndex: 10,
  },
  {
    icon: 'iconzhongzhianniu',
    title: '重置按钮',
    ControlType: 'resetbutton',
    Width: 100,
    Height: 30,
    FontFamily: '微软雅黑',
    FontWeight: 'normal',
    Color: '#000',
    BackColor: '#ddd',
    FontSize: 12,
    TextAlign: 'center',
    BorderWidth: 1,
    Style: 'solid',
    BorderColor: '#000',
    BorderRadius: 10,
    Text: '重置按钮',
    Opacity: 100,
    ZIndex: 10,
  },
  {
    icon: './imgs/icon_Pie.png',
    title: '饼图',
    ControlType: 'piechart',
    Width: 350,
    Height: 350,
    RotateAngle: 0,
    Opacity: 100,
    ZIndex: 10,
  },
  {
    icon: './imgs/icon_dash.png',
    title: '仪表盘',
    ControlType: 'dashboardchart',
    Width: 350,
    Height: 350,
    RotateAngle: 0,
    Opacity: 100,
    ZIndex: 0,
  },
  {
    icon: './imgs/icon_bar.png',
    title: '柱形图',
    ControlType: 'barchart',
    Width: 350,
    Height: 350,
    RotateAngle: 0,
    Opacity: 100,
    ZIndex: 0,
  },
  {
    icon: './imgs/icon_graph.png',
    title: '折线图',
    ControlType: 'linechart',
    Width: 350,
    Height: 350,
    RotateAngle: 0,
    Opacity: 100,
    ZIndex: 0,
  }
]
var Controls = {
  ControlList: []
}
Controls.ControlList = [
  // {
  //   title: '矩形',
  //   ControlType: 'solidrectangle',
  //   Name: 'solidrectangle0',
  //   PropertyList: {
  //     id: 0,
  //     Left: 100,
  //     Top: 500,
  //     Width: 200,
  //     Height: 140,
  //     BackColor: '#fff',
  //     BorderWidth: 2,
  //     Style: 'solid',
  //     BorderColor: '#000',
  //     Opacity: 100,
  //     ZIndex: 10
  //  },
  //   pointList: ['lt', 'rt', 'lb', 'rb', 'l', 'r', 't', 'b'],
  // },
  // {
  //   title: '直线',
  //   ControlType: 'line',
  //   Name: 'line1',
  //   PropertyList: {
  //     id: 1,
  //     Left: 400,
  //     Top: 200,
  //     Width: 100,
  //     BorderWidth: 5,
  //     height: 5,
  //     Style: 'solid',
  //     Opacity: 100,
  //     BorderColor: '#000',
  //     ZIndex: 10
  //  },
  //   pointList: ['l', 'r'],
  // }
]
// 数值显示组件变量表格数据 注：里面数据为测试分页功能使用，可删除
var tableData = [
  {
    data1: '基础采集点',
    data2: 'channeng1',
    data3: '产能1',
    data4: 'KW/h',
    data5: 'int',
    data6: '计算累计',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang2',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang3',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang4',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang5',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang6',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang7',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang8',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang9',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang10',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang11',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang12',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'binliang13',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变量2',
    data4: 'KWh',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianling13',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianling13',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianling13',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianling13',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianling13',
    data3: '变量',
    data4: 'KW/h',
    data5: 'float',
    data6: '计瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bialiang13',
    data3: '变量2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '计算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基采集点1',
    data2: 'bianling13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计瞬时',
    data7: '力源',
    data8: 'Q12',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基采集点1',
    data2: 'bianling13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计瞬时',
    data7: '力源',
    data8: 'Q12',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基采集点1',
    data2: 'bianling13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计瞬时',
    data7: '力源',
    data8: 'Q12',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基采集点1',
    data2: 'bianling13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计瞬时',
    data7: '力源',
    data8: 'Q12',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基采集点1',
    data2: 'bianling13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计瞬时',
    data7: '力源',
    data8: 'Q12',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基采集点1',
    data2: 'bianling13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计瞬时',
    data7: '力源',
    data8: 'Q12',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基采集点1',
    data2: 'bianling13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计瞬时',
    data7: '力源',
    data8: 'Q12',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基采集点1',
    data2: 'bianling13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计瞬时',
    data7: '力源',
    data8: 'Q12',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基采集点1',
    data2: 'bianling13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计瞬时',
    data7: '力源',
    data8: 'Q12',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基采集点1',
    data2: 'bianling13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计瞬时',
    data7: '力源',
    data8: 'Q12',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基采集点1',
    data2: 'bianling13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计瞬时',
    data7: '力源',
    data8: 'Q12',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基采集点1',
    data2: 'bianling13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计瞬时',
    data7: '力源',
    data8: 'Q12',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基采集点1',
    data2: 'bianling13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计瞬时',
    data7: '力源',
    data8: 'Q12',
    data9: 'SYC20200305',
  },
  {
    data1: '最后采集点1',
    data2: 'bianliang13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '时',
    data7: '源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基采集点1',
    data2: 'bianling13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计瞬时',
    data7: '力源',
    data8: 'Q12',
    data9: 'SYC20200305',
  },
  {
    data1: '最后采集点1',
    data2: 'bianliang13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '时',
    data7: '源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基采集点1',
    data2: 'bianling13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计瞬时',
    data7: '力源',
    data8: 'Q12',
    data9: 'SYC20200305',
  },
  {
    data1: '最后采集点1',
    data2: 'bianliang13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '时',
    data7: '源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基采集点1',
    data2: 'bianling13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计瞬时',
    data7: '力源',
    data8: 'Q12',
    data9: 'SYC20200305',
  },
  {
    data1: '最后采集点1',
    data2: 'bianliang13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '时',
    data7: '源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基采集点1',
    data2: 'bianling13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计瞬时',
    data7: '力源',
    data8: 'Q12',
    data9: 'SYC20200305',
  },
  {
    data1: '最后采集点1',
    data2: 'bianliang13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '时',
    data7: '源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基采集点1',
    data2: 'bianling13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计瞬时',
    data7: '力源',
    data8: 'Q12',
    data9: 'SYC20200305',
  },
  {
    data1: '最后采集点1',
    data2: 'bianliang13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '时',
    data7: '源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基采集点1',
    data2: 'bianling13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计瞬时',
    data7: '力源',
    data8: 'Q12',
    data9: 'SYC20200305',
  },
  {
    data1: '最后采集点1',
    data2: 'bianliang13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '时',
    data7: '源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基础采集点1',
    data2: 'bianliang13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '算瞬时',
    data7: '力源',
    data8: 'Q102',
    data9: 'SYC20200305',
  },
  {
    data1: '基采集点1',
    data2: 'bianling13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'float',
    data6: '计瞬时',
    data7: '力源',
    data8: 'Q12',
    data9: 'SYC20200305',
  },
  {
    data1: '最后采集点1',
    data2: 'bianliang13',
    data3: '变2',
    data4: 'KW/h',
    data5: 'floa',
    data6: '时',
    data7: '源',
    data8: 'Q102',
    data9: 'SYC20200305',
  }
]
var pageData = {
  totalCount: tableData.length, // 总条数
  totalPage: 1, // 总页数
  pageIndex: 1, // 当前页
  pageSize: 10, // 每页显示条数
}

Controls.Data = {
    "PieChartItemList":[],
    "DashBoardChartItemList":[],
    "LineChartItemList":[],
    "BarChartItemList":[]
}
